### ISSUE TITLE
Problem Adding MBAutoCompleteTextField completely in code

### ISSUE THREAD

**Issue by TheLordOfTheKings** [MarcBruins/MBAutoComplete#5]
Hi,
First thanks for all of your efforts.
second, i wanted to know how can i use your control with xamarin.ios native codefirst approach?
All the samples are using a .xib as UIView and not doing codes to create and initialize it first.
Also My tryings ends with an unknown obj-c runtime exception. 
Thanks again

**Comment by MarcBruins** [comment]
Hi Arash, you're welcome. I haven't tried it using a code only. Can you provide a sample?

**Comment by MarcBruins** [comment]
Closing, got no response
