### ISSUE TITLE
auto complete not working

### ISSUE THREAD

**Issue by minareadyapps** [MarcBruins/MBAutoComplete#6]
when I enter text in my textfield data not sorted according to this letter  

example I have list that contain xamarin word , it should be in the top of list when I enter xam first three letters  but that not happen with this library 
```
public override void ViewDidLoad()
		{
		
            autoCompleteTextField.Setup(this, new List<string>() { "customizable", "xamarin", "autocomplete", "ios" });
}
```

**Comment by MarcBruins** [comment]
working fine in sample
